server:
  port: ${APP_PORT:10001}
  
spring:
  application:
    name: ${APP_NAME:bear-api-gateway}
    instance_id: ${random.value}
  profiles:
    active: ${PROFILE:dev}
  session:
    store-type: none

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: default
    availabilityZones:
      default: devZone
    preferSameZone: false
    serviceUrl:
      devZone: ${SERVICE_URL:http://${BEAR_EUREKA_IP:127.0.0.1}:${BEAR_EUREKA_PORT:8761}/${registry.name:eureka}/}

hystrix:
  threadpool:
    default:
      coreSize: ${HYSTRIX_THREADPOOL_DEFAULT_CORESIZE:2000}
      maxQueueSize: ${HYSTRIX_THREADPOOL_DEFAULT_MAXQUEUESIZE:1000}
  command:
    default:
      execution:
        timeout: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: ${HYSTRIX_THREAD_TIMEOUTINMILLISECONDS:900000}
ribbon:
  eureka:
    enabled: true
  ReadTimeout: ${RIBBON_READTIMEOUT:300000}
  ConnectTimeout: ${RIBBON_CONNECTTIMEOUT:300000}


security:
  sessions: ALWAYS

management:
  security:
    roles: ROLE_ADMIN
    enabled: ${MANAGEMENT_SECURITY_ENABLED:false}

zuul:
  routes:
    bear-service: 
      path: /service/**
      serviceId: bear-service
  sensitiveHeaders:
  host:
    maxTotalConnections: ${ZUUL_HOST_MAXTOTALCONNECTIONS:1000}
    maxPerRouteconnections: ${ZUUL_HOST_MAXPERROUTECONNECTIONS:50}

jwt:
  token:
    secret: ${TOKEN_SECRET:THISISSECRET}
    expiration: ${TOKEN_EXPIRATION:3600}

auth:
  interface:
    control: ${AUTH_INTERFACE_CONTROL:false}

